import os
import nbformat as nbf
from datetime import datetime

def generate_features_notebook():
    nb = nbf.v4.new_notebook()
    
    # Metadata
    nb.metadata['kernelspec'] = {
        'display_name': 'Python 3',
        'language': 'python',
        'name': 'python3'
    }

    # Title and description
    nb.cells.append(nbf.v4.new_markdown_cell(
        "# Phase 04: Feature Engineering\n"
        "**Context:** Production-First Methodology\n\n"
        "This notebook explores the features generated by the `FeatureEngineer` class. "
        "Following the specific project rules, this phase strictly **enriches historical data** "
        "without extending the dataset with future projections (which are handled in the inference phase).\n\n"
        "**Key Goals:**\n"
        "1. Validate feature distributions on historical data.\n"
        "2. Correlation analysis of engineered features.\n"
        "3. Ensure the dataset maintains its original size (97 rows)."
    ))

    # Cell 1: Setup
    nb.cells.append(nbf.v4.new_code_cell(
        "import pandas as pd\n"
        "import numpy as np\n"
        "import matplotlib.pyplot as plt\n"
        "import seaborn as sns\n"
        "import os\n"
        "from src.utils.config_loader import load_config\n"
        "\n"
        "config = load_config()\n"
        "plt.style.use('ggplot')\n"
        "sns.set_palette('viridis')\n"
        "print('Setup complete.')"
    ))

    # Cell 2: Load Data
    nb.cells.append(nbf.v4.new_code_cell(
        "# Load the engineered features dataset\n"
        "features_path = os.path.join(config['general']['paths']['features'], 'master_features.parquet')\n"
        "df = pd.read_parquet(features_path)\n"
        "print(f'Shape of features dataset: {df.shape}')\n"
        "\n"
        "# Integrity check\n"
        "expected_rows = 97\n"
        "assert len(df) == expected_rows, f'Error: Expected {expected_rows} rows, but got {len(df)}'\n"
        "print(f'✅ Integrity check passed: {len(df)} rows.')\n"
        "df.tail(10)"
    ))

    # Cell 3: Visualizing Cyclical Features
    nb.cells.append(nbf.v4.new_code_cell(
        "# Check cyclical features (Sin/Cos)\n"
        "cols = ['month_sin', 'month_cos', 'quarter_sin', 'quarter_cos', 'semester_sin', 'semester_cos']\n"
        "df[cols].plot(figsize=(15, 6), title='Cyclical Features over Time')\n"
        "plt.show()"
    ))

    # Cell 4: Technical and Trend Features
    nb.cells.append(nbf.v4.new_code_cell(
        "# Examine business and technical features\n"
        "tech_cols = ['is_pandemic', 'novenas_intensity', 'is_bonus_month', 'weekend_days_count', \n"
        "             'days_in_month', 'holidays_count', 'time_drift_index']\n"
        "df[tech_cols].tail(12).style.background_gradient(cmap='Blues')"
    ))

    # Cell 5: Target Interaction
    nb.cells.append(nbf.v4.new_code_cell(
        "# Visualizing relationship between Novenas/Bonus and Units\n"
        "fig, ax1 = plt.subplots(figsize=(15, 6))\n"
        "ax2 = ax1.twinx()\n"
        "df['total_unidades_entregadas'].plot(ax=ax1, color='gray', alpha=0.5, label='Units')\n"
        "df['novenas_intensity'].plot(ax=ax2, color='red', style='--', label='Novenas')\n"
        "df['is_bonus_month'].plot(ax=ax2, color='blue', alpha=0.3, label='Bonus Month')\n"
        "plt.title('Business Events vs Units')\n"
        "plt.legend()\n"
        "plt.show()"
    ))

    # Cell 6: Correlation Matrix
    nb.cells.append(nbf.v4.new_code_cell(
        "# Correlation with target\n"
        "target = config['preprocessing']['target_variable']\n"
        "corr = df.corr()[target].sort_values(ascending=False)\n"
        "plt.figure(figsize=(10, 10))\n"
        "sns.barplot(x=corr.values, y=corr.index)\n"
        "plt.title(f'Correlation with Target ({target})')\n"
        "plt.show()"
    ))

    # Save notebook
    nb_path = 'notebooks/04_feature_engineering.ipynb'
    with open(nb_path, 'w', encoding='utf-8') as f:
        nbf.write(nb, f)
    
    print(f'✅ Notebook {nb_path} generated successfully.')

if __name__ == '__main__':
    generate_features_notebook()
